"""empty message

Revision ID: b309eb3d3f06
Revises: d0eb842b7398
Create Date: 2021-05-17 16:42:37.006945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b309eb3d3f06'
down_revision = 'd0eb842b7398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_status', sa.String(length=255), nullable=True),
    sa.Column('task_time', sa.DateTime(), nullable=True),
    sa.Column('task_score', sa.Integer(), nullable=True),
    sa.Column('task_flag', sa.String(length=255), nullable=False),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['front_user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('front_user_ibfk_1', 'front_user', type_='foreignkey')
    op.drop_column('front_user', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('task_id', mysql.VARCHAR(length=100), nullable=True))
    op.create_foreign_key('front_user_ibfk_1', 'front_user', 'task', ['task_id'], ['id'])
    op.drop_table('work')
    # ### end Alembic commands ###
