"""empty message

Revision ID: de86fdc76b44
Revises: 6177715393bc
Create Date: 2021-05-07 17:30:07.614884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de86fdc76b44'
down_revision = '6177715393bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('flag', sa.String(length=255), nullable=False),
    sa.Column('creat_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('front_user', sa.Column('task_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'front_user', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'front_user', type_='foreignkey')
    op.drop_column('front_user', 'task_id')
    op.drop_table('task')
    # ### end Alembic commands ###
